spring:
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
      hibernate:
        ddl-auto: update

    datasource:
        url: jdbc-secretsmanager:postgresql://<DBURL>
        username: test/asm
        driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver

